env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: build-scanner-clair
    main: ./cmd/harbor-scanner-clair/main.go
    binary: scanner-clair
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
dockers:
  - image_templates:
      - "docker.io/goharbor/harbor-scanner-clair:{{ .Version }}"
    binaries:
      - scanner-clair
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.name={{ .ProjectName }}"
      - "--label=org.label-schema.description=Harbor scanner adapter for Clair"
      - "--label=org.label-schema.version={{ .Version }}"
      - "--label=org.label-schema.build-date={{ .Date }}"
      - "--label=org.label-schema.vcs=https://github.com/goharbor/harbor-scanner-clair"
      - "--label=org.label-schema.vcs-ref={{ .FullCommit }}"
